"""add plaid balance connection

Revision ID: 4553e3440cb6
Revises: d5f6a7b8c9d1
Create Date: 2026-05-17 04:07:06.430847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4553e3440cb6'
down_revision = 'd5f6a7b8c9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_mask', sa.String(length=10), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('iso_currency_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_balance_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=64), nullable=True),
    sa.Column('last_sync_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plaid_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_connections_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_plaid_connection_active_user', ['user_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_connections', schema=None) as batch_op:
        batch_op.drop_index('uq_plaid_connection_active_user', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))
        batch_op.drop_index(batch_op.f('ix_plaid_connections_user_id'))

    op.drop_table('plaid_connections')
    # ### end Alembic commands ###
