"""drop legacy user subscription columns

Revision ID: fc9e4136ef56
Revises: 92d6f98b8d33
Create Date: 2026-04-26 00:42:05.665257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9e4136ef56'
down_revision = '92d6f98b8d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_source')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_expiry')
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subscription_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(length=20), server_default=sa.text("'inactive'"), nullable=False))
        batch_op.add_column(sa.Column('subscription_source', sa.VARCHAR(length=20), server_default=sa.text("'none'"), nullable=False))

    # ### end Alembic commands ###
