name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: python:3.11-alpine

    steps:
    - uses: actions/checkout@v3
    - name: pycashflow
      run: docker build . --file Dockerfile --tag pycashflow:$(date +%s)
